name : First Workflow script 

on:
  push:
    branches:
      - main



jobs:
  first-build-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: "Repo files checkout"
        uses: actions/checkout@v4

      - name: "Docker Image build"
        run: docker image build -t flask-app:v1 -f app/Dockerfile app/

      - name: "Docker container run"
        run: docker container run -d --name flaskapp -p 5000:5000 flask-app:v1

      - name: "Docker container check"
        run : docker container ls -a

      - name: "Check container logs"
        run: docker logs flaskapp

      - name: "Check the flask app status"
        run: ./app/check.sh







